### ISSUE TITLE
ubuntu22.04 does not work

### ISSUE THREAD

**Issue by zhenda-hub** [oviniciusfeitosa/obsidian-ubuntu-installer#1]
I run in my ubuntu 22.04 

```bash
sudo curl -fsSL https://raw.githubusercontent.com/oviniciusfeitosa/obsidian-ubuntu-installer/main/install.sh | sh
```
I got

```bash
mv: cannot move 'squashfs-root' to '/opt/Obsidian/squashfs-root': directory is not empty
Creating a symbolic link to /usr/local/bin/obsidian
ln: cannot create symbolic link '/usr/local/bin/obsidian': insufficient permissions
Creating a desktop entry
Obsidian 1.6.7 installed successfully!
```

**Comment by oviniciusfeitosa** [comment]
Thanks for sharing @zhenda-hub  .

I analyzed the output and it shows that the `/opt/Obsidian` directory already has content. I added a validation so that if there is already content in this directory, it will stop the installation.

Regarding the error `ln: cannot create symbolic link '/usr/local/bin/obsidian': insufficient permissions`, it is caused because your current user does not have permission to create a symbolic link within the `/usr/local/bin/` directory. I just uploaded a tweak to run this command with the necessary privileges.

I suggest you make a backup of your `/opt/Obsidian` directory and move it to another location, for example `mv /opt/Obsidian /opt/bkp_Obsidian` and run the script again.

Could you try again?
